# Configurações do Site
title: "Smartex"
slogan: "Startup voltada para heveicultura de precisão"
email: smartexagro@gmail.com
description: >- # Alterar apenas nas linhas abaixo
  Nosso objetivo é desenvolver soluções de automação agrícola para seringueiras 
  e gerar novas técnicas de manejo para heveicultura capazes de superar o método 
  atual e entregar ganhos em produtividade, economia, padronização da sangria, 
  borracha de maior qualidade, maior longevidade e apropriação do processo de explotação
baseurl: "/"
url: "https://smartex.agr.br"
# Mídias Sociais
twitter_username: smartexagro
github_username: smartexagro
youtube_username: UCgCxamxZSoTWMM0hwSNdWdA
intagram_username: smartexagro
facebook_username: smartexagro

# Estilo dos Permalinks
permalink: pretty

# Serviços de Rastramento
google_analytics_key: UA-128989682-1

# Conteudos
collections:
  blocks:
    output: true

# Configurações do Build
markdown: kramdown
sass:
  style: :compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-menus

# Ignora os arquivos do sistema
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.txt
- CNAME
- seo-keywords.md
