# Configurações do Site
title: Smartex
email: smartexagro@gmail.com
description: >- # Alterar apenas nas linhas abaixo
  Heveicultura de Precisão
baseurl: "/"
url: ""
twitter_username: smartexagro
github_username: smartexagro
youtube_username: UCgCxamxZSoTWMM0hwSNdWdA
intagram_username: smartexagro
facebook_username: smartexagro

# Conteudos
collections:
  blocks:
    output: true

# Configurações do Build
markdown: kramdown
sass:
  style: :compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-menus

# Ignora os arquivos do sistema
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.txt
- CNAME
