---
new_page_extension: md
auto_deploy: true
admin_path: painel
webhook_url: 
sections:
- type: directory
  path: _blocks
  label: Blocos
  create: documents
  match: "**/*"
- type: jekyll-pages
  label: Paginas
  create: all
- type: directory
  path: _posts
  label: Postagens
  create: documents
  match: "**/*"
upload_dir: "./uploads"
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
